name: Deploy to deta.sh
on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "deploy" ]
  workflow_dispatch:
    inputs:
      init_mode:
        description: 'init mode'
        required: false
        type: boolean
      update_env:
        description: 'update env'
        required: false
        type: boolean
#      visor_enable:
#        description: 'visor enable'
#        required: false
#        type: boolean
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
      - if: ${{ inputs.init_mode }}
        name: Create micro on Deta
        uses: jhihyulin/deta-create-micro-action@v1.0.0
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN }}
          deta-name: 'ShortURL-main'
          deta-project: ${{ secrets.DETA_PROJECT_NAME }}
          deta-project-dir: 'micros/ShortURL-main'
          deta-python-version: 'python3.9'
      - if: ${{ inputs.update_env }}
        name: Update environment on Deta
        uses: jhihyulin/deta-update-env-action@v1.0.0-alpha.0
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN }}
          deta-name: 'ShortURL-main'
          deta-project: ${{ secrets.DETA_PROJECT_NAME }}
          deta-project-dir: 'micros/ShortURL-main'
      - name: deploy ShortURL-main
        uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN }} #Deta access token https://docs.deta.sh/docs/cli/auth
          deta-name: 'ShortURL-main' #Deta Micro name https://docs.deta.sh/docs/cli/commands/#deta-clone
          deta-project: ${{ secrets.DETA_PROJECT_NAME }} #Optional: Deta project name https://docs.deta.sh/docs/cli/commands/#deta-clone
          deta-project-dir: 'micros/ShortURL-main' #Optional: directory to be deployed on Deta. Default is the root "."
